# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fyy_inke' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fyy_inke
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension'
pod 'LFLiveKit'
pod 'YYKit'
pod 'Masonry'
pod 'LFLiveKit'

end
